# Generated by Django 5.1.7 on 2025-03-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarListing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
